version: '3'

networks:
  byteoffice:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: bo_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - byteoffice

  mysql:
    image: mysql:5.7.29
    container_name: bo_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: byteoffice
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - byteoffice

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bo_php
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - byteoffice

  composer:
    image: composer:latest
    container_name: bo_composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - byteoffice

  npm:
    image: node:13.7
    container_name: bo_npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - byteoffice

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bo_artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - byteoffice
